In [2]:
import numpy as np

In [3]:
mylist = [[1,2,3],
         [4,5,6],
         [7,8,9]]

In [4]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
pa=np.array(mylist)

In [7]:
pa.shape

(3, 3)

In [9]:
np.arange(0,26)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [11]:
np.zeros((4,10)) + 4

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [13]:
np.ones((3,2))*10

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

In [16]:
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [24]:
# Creating an identity metrics
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
ax=np.random.randint(0,10,100)
len(ax)

100

In [36]:
ax.reshape(10,10)

array([[1, 9, 9, 1, 2, 0, 5, 0, 9, 6],
       [3, 2, 6, 0, 8, 8, 1, 0, 9, 8],
       [1, 0, 8, 6, 5, 8, 2, 5, 7, 6],
       [2, 9, 4, 1, 7, 1, 9, 2, 4, 5],
       [8, 5, 9, 4, 4, 2, 6, 9, 4, 5],
       [7, 3, 4, 0, 0, 0, 7, 1, 6, 5],
       [7, 2, 4, 7, 4, 0, 8, 8, 5, 3],
       [7, 5, 2, 9, 1, 9, 6, 0, 7, 5],
       [4, 3, 3, 7, 0, 4, 6, 5, 8, 9],
       [7, 4, 1, 0, 4, 3, 7, 1, 1, 3]])

In [37]:
# showing the index location of the maximum number
ax.argmax()

1

In [38]:
ax.argmin()

5

In [40]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
bool_arr=arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
arr[bool_arr]*10

array([ 50,  60,  70,  80,  90, 100])

In [45]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [46]:
arr +arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [49]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

# PANDAS SECTION

## Pandas Series

In [50]:
import numpy as np
import pandas as pd

In [52]:
mylist=[10,20,30]
arr=np.array(mylist)
arr

array([10, 20, 30])

In [53]:
d={'a':10,'b':20,'c':30}

In [55]:
pd.Series(mylist)

0    10
1    20
2    30
dtype: int64

In [58]:
pa=pd.Series(d)
pa

a    10
b    30
c    40
dtype: int64

In [61]:
pa['g']=10

In [62]:
pa

a    10
b    30
c    40
g    10
dtype: object

In [65]:
np.random.seed(0)
rand_mat = np.random.randn(5,4)
rand_mat

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [70]:
pd.DataFrame(rand_mat, columns=['Gambia', 'Senegal','Guanea','Mali'],
             index= ['First', 'Second', 'Third', 'Forth', 'Fith'])

Gambia   Senegal    Geunea      Mali
First   1.764052  0.400157  0.978738  2.240893
Second  1.867558 -0.977278  0.950088 -0.151357
Third  -0.103219  0.410599  0.144044  1.454274
Forth   0.761038  0.121675  0.443863  0.333674
Fift    1.494079 -0.205158  0.313068 -0.854096

In [74]:
# We can also do as
df =pd.DataFrame(rand_mat,index = 'First Second Third Forth Fith'.split(),columns='Gambia Senegal Guanea Mali'.split())

In [75]:
df

Gambia   Senegal    Guanea      Mali
First   1.764052  0.400157  0.978738  2.240893
Second  1.867558 -0.977278  0.950088 -0.151357
Third  -0.103219  0.410599  0.144044  1.454274
Forth   0.761038  0.121675  0.443863  0.333674
Fith    1.494079 -0.205158  0.313068 -0.854096

In [76]:
df['New']=df['Gambia']+df['Mali']

In [77]:
df

Gambia   Senegal    Guanea      Mali       New
First   1.764052  0.400157  0.978738  2.240893  4.004946
Second  1.867558 -0.977278  0.950088 -0.151357  1.716201
Third  -0.103219  0.410599  0.144044  1.454274  1.351055
Forth   0.761038  0.121675  0.443863  0.333674  1.094712
Fith    1.494079 -0.205158  0.313068 -0.854096  0.639983

In [79]:
df = df.drop('New', axis=1)
df

Gambia   Senegal    Guanea      Mali
First   1.764052  0.400157  0.978738  2.240893
Second  1.867558 -0.977278  0.950088 -0.151357
Third  -0.103219  0.410599  0.144044  1.454274
Forth   0.761038  0.121675  0.443863  0.333674
Fith    1.494079 -0.205158  0.313068 -0.854096

In [80]:
df>0

Gambia  Senegal  Guanea   Mali
First     True     True    True   True
Second    True    False    True  False
Third    False     True    True   True
Forth     True     True    True   True
Fith      True    False    True  False

In [81]:
df_bool=df>0
df_bool

Gambia  Senegal  Guanea   Mali
First     True     True    True   True
Second    True    False    True  False
Third    False     True    True   True
Forth     True     True    True   True
Fith      True    False    True  False

In [84]:
df1=df[df_bool]
df1

Gambia   Senegal    Guanea      Mali
First   1.764052  0.400157  0.978738  2.240893
Second  1.867558       NaN  0.950088       NaN
Third        NaN  0.410599  0.144044  1.454274
Forth   0.761038  0.121675  0.443863  0.333674
Fith    1.494079       NaN  0.313068       NaN

In [85]:
df1.isnull().sum()

Gambia     1
Senegal    2
Guanea     0
Mali       2
dtype: int64

In [86]:
df

Gambia   Senegal    Guanea      Mali
First   1.764052  0.400157  0.978738  2.240893
Second  1.867558 -0.977278  0.950088 -0.151357
Third  -0.103219  0.410599  0.144044  1.454274
Forth   0.761038  0.121675  0.443863  0.333674
Fith    1.494079 -0.205158  0.313068 -0.854096

In [90]:
df.loc['Second']

Gambia     1.867558
Senegal   -0.977278
Guanea     0.950088
Mali      -0.151357
Name: Second, dtype: float64

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, First to Fith
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Gambia   5 non-null      float64
 1   Senegal  5 non-null      float64
 2   Guanea   5 non-null      float64
 3   Mali     5 non-null      float64
dtypes: float64(4)
memory usage: 360.0+ bytes


In [97]:
df.describe()

Gambia   Senegal    Guanea      Mali
count  5.000000  5.000000  5.000000  5.000000
mean   1.156702 -0.050001  0.565960  0.604678
std    0.826433  0.576234  0.379083  1.242182
min   -0.103219 -0.977278  0.144044 -0.854096
25%    0.761038 -0.205158  0.313068 -0.151357
50%    1.494079  0.121675  0.443863  0.333674
75%    1.764052  0.400157  0.950088  1.454274
max    1.867558  0.410599  0.978738  2.240893

In [98]:
data = {'Platform':['FB', 'Google', 'TWitter', 'Inst','Snap'],
       'Users':['Lan','Sau', 'fato', 'Mari','Ebri'],
       'Sales':[100,400, 2500, 5009,300]}

In [99]:
my=pd.DataFrame(data)

In [100]:
my

Platform Users  Sales
0       FB   Lan    100
1   Google   Sau    400
2  TWitter  fato   2500
3     Inst  Mari   5009
4     Snap  Ebri    300

In [104]:
my.groupby('Users').max()

Platform  Sales
Users                
Ebri      Snap    300
Lan         FB    100
Mari      Inst   5009
Sau     Google    400
fato   TWitter   2500

In [108]:
my.groupby('Platform').describe().T

Platform        FB  Google    Inst   Snap  TWitter
Sales count    1.0     1.0     1.0    1.0      1.0
      mean   100.0   400.0  5009.0  300.0   2500.0
      std      NaN     NaN     NaN    NaN      NaN
      min    100.0   400.0  5009.0  300.0   2500.0
      25%    100.0   400.0  5009.0  300.0   2500.0
      50%    100.0   400.0  5009.0  300.0   2500.0
      75%    100.0   400.0  5009.0  300.0   2500.0
      max    100.0   400.0  5009.0  300.0   2500.0

In [110]:
my

Platform Users  Sales
0       FB   Lan    100
1   Google   Sau    400
2  TWitter  fato   2500
3     Inst  Mari   5009
4     Snap  Ebri    300

In [111]:
my.sort_values('Sales')

Platform Users  Sales
0       FB   Lan    100
4     Snap  Ebri    300
1   Google   Sau    400
2  TWitter  fato   2500
3     Inst  Mari   5009

In [117]:
pd.read_csv('example.csv')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [119]:
pd.read_csv('bank.csv')

age            job  marital  education default  balance housing loan  \
0      30     unemployed  married    primary      no     1787      no   no   
1      33       services  married  secondary      no     4789     yes  yes   
2      35     management   single   tertiary      no     1350     yes   no   
3      30     management  married   tertiary      no     1476     yes  yes   
4      59    blue-collar  married  secondary      no        0     yes   no   
...   ...            ...      ...        ...     ...      ...     ...  ...   
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
0     cellular   19   oct        79         1     -1         0  unknown  no  
1     cellular   11   may       220         1    339         4  failure  no  
2     cellular   16   apr       185         1    330         1  failure  no  
3      unknown    3   jun       199         4     -1         0  unknown  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4517   unknown    9   may       153         1     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  
4520  cellular    3   apr       345         2    249         7    other  no  

[4521 rows x 17 columns]

In [121]:
df=pd.read_excel('Excel_Sample.xlsx')
df

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [125]:
df=df.drop('Unnamed: 0', axis=1)

In [126]:
import torch

ModuleNotFoundError: No module named 'torch'

In [127]:
conda activate pytorch_p37


CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



Note: you may need to restart the kernel to use updated packages.


In [128]:
pip install pytorch

  ERROR: Command errored out with exit status 1:
   command: /home/bakary/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wvarpgt6/pytorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wvarpgt6/pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rfppv9l7
       cwd: /tmp/pip-install-wvarpgt6/pytorch/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-wvarpgt6/pytorch/setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  ----------------------------------------
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
    Running setup.py install for pytorch