In [3]:
import torch
import numpy as np

In [5]:
torch.__version__

'1.8.0'

In [32]:
arr = np.random.randint(2,10, 10)
arr

array([4, 3, 7, 6, 4, 7, 9, 7, 9, 2])

## HOW TO CREATE TENSOR FROM NUMPY ARRAY

Let's convert numpy array to tensor

In [33]:
x = torch.from_numpy(arr)
x

tensor([4, 3, 7, 6, 4, 7, 9, 7, 9, 2])

In [34]:
# Or we can also do as
x1=torch.as_tensor(arr)
x1

tensor([4, 3, 7, 6, 4, 7, 9, 7, 9, 2])

In [35]:
# 2-d numpy array
arr2d = np.arange(0,20)
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
x2=arr2d.reshape(4,5)
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
y = torch.as_tensor(x2)
y

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [38]:
arr[0]=99

In [39]:
arr

array([99,  3,  7,  6,  4,  7,  9,  7,  9,  2])

In [40]:
x

tensor([99,  3,  7,  6,  4,  7,  9,  7,  9,  2])

## HOW TO CREATE TENSOR WITH PYTORCH FORM SCRACH

In [42]:
# Torsor Place Holder
torch.empty(4,2)

tensor([[6.7333e+22, 1.7591e+22],
        [1.7184e+25, 4.3222e+27],
        [6.1972e-04, 7.2443e+22],
        [1.7728e+28, 7.0367e+22]])

In [43]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [44]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [46]:
torch.arange(0,20).reshape(4,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [47]:
torch.tensor([1,2,3,4,5,6])

tensor([1, 2, 3, 4, 5, 6])

Random numbers from tensor

In [48]:
# Tensor random numbers of uniform distributions
torch.rand(4,3)

tensor([[0.8657, 0.3383, 0.5095],
        [0.9464, 0.2530, 0.9477],
        [0.0531, 0.3740, 0.8765],
        [0.7552, 0.1879, 0.8214]])

In [49]:
# Tensor random numbers of normal distribution
# Where, Mean = 0 and standard deviation =1
t = torch.randn(4,3)
t

tensor([[-0.9537, -1.6725, -0.4997],
        [-0.5674,  2.6577,  1.8006],
        [-0.4469, -0.4941,  0.9150],
        [ 1.4258, -0.0161, -0.4007]])

In [52]:
# tensor random integers
torch.randint(0,10,size=(5,5))

tensor([[6, 1, 8, 4, 6],
        [8, 1, 6, 0, 1],
        [8, 6, 8, 8, 4],
        [6, 6, 3, 3, 3],
        [3, 6, 8, 9, 5]])

In [53]:
x=torch.zeros(5,3)

In [54]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [55]:
torch.rand_like(x)

tensor([[0.6666, 0.5946, 0.1952],
        [0.2154, 0.4406, 0.6694],
        [0.8102, 0.1839, 0.7952],
        [0.9654, 0.3683, 0.3655],
        [0.6460, 0.3605, 0.3233]])

In [56]:
torch.randn_like(x)

tensor([[ 0.1071,  0.8792,  0.8036],
        [-1.1059, -0.6395,  0.7078],
        [-0.9604,  0.5079,  0.9171],
        [-0.3950,  0.4817,  1.4965],
        [ 0.1467, -0.6336, -0.3668]])

In [61]:
torch.randint_like(x,0,10)

tensor([[9., 8., 8.],
        [6., 7., 0.],
        [5., 2., 6.],
        [5., 0., 4.],
        [4., 4., 0.]])

In [63]:
# Setting up random seed
torch.manual_seed(42)
u = torch.rand(2,4)
u

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [64]:
u

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

#### iNDEXING AND SLICING WITH PYTORCH IN TENSOR

In [70]:
y = torch.arange(6).reshape(3,2) 

In [71]:
y

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [72]:
y[1,1]

tensor(3)

In [74]:
y[1,:]

tensor([2, 3])

In [76]:
a= torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [77]:
b = torch.tensor([[7,8],[9,10],[11,12]])
b

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [78]:
torch.mm(a,b)

tensor([[ 58,  64],
        [139, 154]])

In [80]:
a@b

tensor([[ 58,  64],
        [139, 154]])